# fly.toml app configuration file generated for the-knower-system on 2026-08-07T21:44:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'the-knower-system'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
