import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
        './resources/js/**/*.js',
    ],

    theme: {
        extend: {
            colors: {
                "on-primary": "var(--on-primary)",
                "surface-container-low": "var(--surface-container-low)",
                "surface-bright": "var(--surface-bright)",
                "warning-amber": "var(--warning-amber)",
                "obsidian-surface": "var(--obsidian-surface)",
                "secondary-fixed": "var(--secondary-fixed)",
                "on-tertiary": "var(--on-tertiary)",
                "error-rose": "var(--error-rose)",
                "surface-tint": "var(--surface-tint)",
                "outline-variant": "var(--outline-variant)",
                "on-surface-variant": "var(--on-surface-variant)",
                "tertiary-container": "var(--tertiary-container)",
                "surface-container": "var(--surface-container)",
                "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
                "ai-purple": "var(--ai-purple)",
                "on-tertiary-fixed": "var(--on-tertiary-fixed)",
                "primary-fixed-dim": "var(--primary-fixed-dim)",
                "surface-container-highest": "var(--surface-container-highest)",
                "on-secondary-container": "var(--on-secondary-container)",
                "error": "var(--error)",
                "inverse-primary": "var(--inverse-primary)",
                "error-container": "var(--error-container)",
                "on-tertiary-container": "var(--on-tertiary-container)",
                "obsidian-base": "var(--obsidian-base)",
                "on-secondary": "var(--on-secondary)",
                "secondary-fixed-dim": "var(--secondary-fixed-dim)",
                "on-secondary-fixed": "var(--on-secondary-fixed)",
                "on-background": "var(--on-background)",
                "outline": "var(--outline)",
                "surface-container-lowest": "var(--surface-container-lowest)",
                "info-cyan": "var(--info-cyan)",
                "on-error-container": "var(--on-error-container)",
                "tertiary": "var(--tertiary)",
                "surface-variant": "var(--surface-variant)",
                "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
                "primary-fixed": "var(--primary-fixed)",
                "success-emerald": "var(--success-emerald)",
                "on-surface": "var(--on-surface)",
                "background": "var(--background)",
                "secondary-container": "var(--secondary-container)",
                "surface": "var(--surface)",
                "surface-dim": "var(--surface-dim)",
                "obsidian-elevated": "var(--obsidian-elevated)",
                "on-error": "var(--on-error)",
                "secondary": "var(--secondary)",
                "primary": "var(--primary)",
                "on-primary-fixed": "var(--on-primary-fixed)",
                "surface-container-high": "var(--surface-container-high)",
                "tertiary-fixed": "var(--tertiary-fixed)",
                "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
                "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
                "primary-container": "var(--primary-container)",
                "inverse-on-surface": "var(--inverse-on-surface)",
                "on-primary-container": "var(--on-primary-container)",
                "inverse-surface": "var(--inverse-surface)",
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "gutter": "24px",
                "margin-desktop": "64px",
                "margin-mobile": "16px",
                "base": "4px",
                "container-max": "1440px"
            },
            fontFamily: {
                "label-sm": ["JetBrains Mono", ...defaultTheme.fontFamily.sans],
                "label-md": ["JetBrains Mono", ...defaultTheme.fontFamily.sans],
                "headline-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "headline-lg-mobile": ["Inter", ...defaultTheme.fontFamily.sans],
                "body-md": ["Inter", ...defaultTheme.fontFamily.sans],
                "body-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "display-lg": ["Inter", ...defaultTheme.fontFamily.sans],
                "body-sm": ["Inter", ...defaultTheme.fontFamily.sans],
                "headline-md": ["Inter", ...defaultTheme.fontFamily.sans],
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                "label-sm": ["12px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500" }],
                "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
                "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
                "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
            },
            transitionProperty: {
                'width': 'width',
                'spacing': 'margin, padding',
            }
        },
    },

    plugins: [forms],
};
