/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicAiSolutionsRouteImport } from './routes/_public.ai-solutions'
import { Route as PublicClientsRouteImport } from './routes/_public.clients'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicDomainsRouteImport } from './routes/_public.domains'
import { Route as PublicDownloadsRouteImport } from './routes/_public.downloads'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicHostingRouteImport } from './routes/_public.hosting'
import { Route as PublicIndustriesRouteImport } from './routes/_public.industries'
import { Route as PublicMaintenanceRouteImport } from './routes/_public.maintenance'
import { Route as PublicPartnersRouteImport } from './routes/_public.partners'
import { Route as PublicPressRouteImport } from './routes/_public.press'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicResourcesRouteImport } from './routes/_public.resources'
import { Route as PublicStatusRouteImport } from './routes/_public.status'
import { Route as PublicSupportRouteImport } from './routes/_public.support'
import { Route as PublicTeamRouteImport } from './routes/_public.team'
import { Route as PublicTechnologiesRouteImport } from './routes/_public.technologies'
import { Route as PublicTestimonialsRouteImport } from './routes/_public.testimonials'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'
import { Route as PublicCareersIndexRouteImport } from './routes/_public.careers.index'
import { Route as PublicCareersSlugRouteImport } from './routes/_public.careers.$slug'
import { Route as PublicCaseStudiesIndexRouteImport } from './routes/_public.case-studies.index'
import { Route as PublicCaseStudiesSlugRouteImport } from './routes/_public.case-studies.$slug'
import { Route as PublicDocsIndexRouteImport } from './routes/_public.docs.index'
import { Route as PublicDocsSlugRouteImport } from './routes/_public.docs.$slug'
import { Route as PublicLegalDocRouteImport } from './routes/_public.legal.$doc'
import { Route as PublicPortfolioIndexRouteImport } from './routes/_public.portfolio.index'
import { Route as PublicPortfolioSlugRouteImport } from './routes/_public.portfolio.$slug'
import { Route as PublicProductsIndexRouteImport } from './routes/_public.products.index'
import { Route as PublicProductsSlugRouteImport } from './routes/_public.products.$slug'
import { Route as PublicServicesIndexRouteImport } from './routes/_public.services.index'
import { Route as PublicServicesSlugRouteImport } from './routes/_public.services.$slug'
import { Route as PublicSolutionsIndexRouteImport } from './routes/_public.solutions.index'
import { Route as PublicSolutionsIndustryRouteImport } from './routes/_public.solutions.$industry'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAiSolutionsRoute = PublicAiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => PublicRoute,
} as any)
const PublicClientsRoute = PublicClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDomainsRoute = PublicDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDownloadsRoute = PublicDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHostingRoute = PublicHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => PublicRoute,
} as any)
const PublicIndustriesRoute = PublicIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMaintenanceRoute = PublicMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPartnersRoute = PublicPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPressRoute = PublicPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStatusRoute = PublicStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSupportRoute = PublicSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeamRoute = PublicTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTechnologiesRoute = PublicTechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTestimonialsRoute = PublicTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCareersIndexRoute = PublicCareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCareersSlugRoute = PublicCareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCaseStudiesIndexRoute = PublicCaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCaseStudiesSlugRoute = PublicCaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsIndexRoute = PublicDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsSlugRoute = PublicDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalDocRoute = PublicLegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortfolioIndexRoute = PublicPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortfolioSlugRoute = PublicPortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsSlugRoute = PublicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesSlugRoute = PublicServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSolutionsIndexRoute = PublicSolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSolutionsIndustryRoute = PublicSolutionsIndustryRouteImport.update({
  id: '/solutions/$industry',
  path: '/solutions/$industry',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/ai-solutions': typeof PublicAiSolutionsRoute
  '/clients': typeof PublicClientsRoute
  '/contact': typeof PublicContactRoute
  '/domains': typeof PublicDomainsRoute
  '/downloads': typeof PublicDownloadsRoute
  '/events': typeof PublicEventsRoute
  '/faq': typeof PublicFaqRoute
  '/hosting': typeof PublicHostingRoute
  '/industries': typeof PublicIndustriesRoute
  '/maintenance': typeof PublicMaintenanceRoute
  '/partners': typeof PublicPartnersRoute
  '/press': typeof PublicPressRoute
  '/pricing': typeof PublicPricingRoute
  '/resources': typeof PublicResourcesRoute
  '/status': typeof PublicStatusRoute
  '/support': typeof PublicSupportRoute
  '/team': typeof PublicTeamRoute
  '/technologies': typeof PublicTechnologiesRoute
  '/testimonials': typeof PublicTestimonialsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/careers/$slug': typeof PublicCareersSlugRoute
  '/case-studies/$slug': typeof PublicCaseStudiesSlugRoute
  '/docs/$slug': typeof PublicDocsSlugRoute
  '/legal/$doc': typeof PublicLegalDocRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/solutions/$industry': typeof PublicSolutionsIndustryRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/careers/': typeof PublicCareersIndexRoute
  '/case-studies/': typeof PublicCaseStudiesIndexRoute
  '/docs/': typeof PublicDocsIndexRoute
  '/portfolio/': typeof PublicPortfolioIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/services/': typeof PublicServicesIndexRoute
  '/solutions/': typeof PublicSolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/ai-solutions': typeof PublicAiSolutionsRoute
  '/clients': typeof PublicClientsRoute
  '/contact': typeof PublicContactRoute
  '/domains': typeof PublicDomainsRoute
  '/downloads': typeof PublicDownloadsRoute
  '/events': typeof PublicEventsRoute
  '/faq': typeof PublicFaqRoute
  '/hosting': typeof PublicHostingRoute
  '/industries': typeof PublicIndustriesRoute
  '/maintenance': typeof PublicMaintenanceRoute
  '/partners': typeof PublicPartnersRoute
  '/press': typeof PublicPressRoute
  '/pricing': typeof PublicPricingRoute
  '/resources': typeof PublicResourcesRoute
  '/status': typeof PublicStatusRoute
  '/support': typeof PublicSupportRoute
  '/team': typeof PublicTeamRoute
  '/technologies': typeof PublicTechnologiesRoute
  '/testimonials': typeof PublicTestimonialsRoute
  '/': typeof PublicIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/careers/$slug': typeof PublicCareersSlugRoute
  '/case-studies/$slug': typeof PublicCaseStudiesSlugRoute
  '/docs/$slug': typeof PublicDocsSlugRoute
  '/legal/$doc': typeof PublicLegalDocRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/solutions/$industry': typeof PublicSolutionsIndustryRoute
  '/blog': typeof PublicBlogIndexRoute
  '/careers': typeof PublicCareersIndexRoute
  '/case-studies': typeof PublicCaseStudiesIndexRoute
  '/docs': typeof PublicDocsIndexRoute
  '/portfolio': typeof PublicPortfolioIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/solutions': typeof PublicSolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/ai-solutions': typeof PublicAiSolutionsRoute
  '/_public/clients': typeof PublicClientsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/domains': typeof PublicDomainsRoute
  '/_public/downloads': typeof PublicDownloadsRoute
  '/_public/events': typeof PublicEventsRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/hosting': typeof PublicHostingRoute
  '/_public/industries': typeof PublicIndustriesRoute
  '/_public/maintenance': typeof PublicMaintenanceRoute
  '/_public/partners': typeof PublicPartnersRoute
  '/_public/press': typeof PublicPressRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/resources': typeof PublicResourcesRoute
  '/_public/status': typeof PublicStatusRoute
  '/_public/support': typeof PublicSupportRoute
  '/_public/team': typeof PublicTeamRoute
  '/_public/technologies': typeof PublicTechnologiesRoute
  '/_public/testimonials': typeof PublicTestimonialsRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/careers/$slug': typeof PublicCareersSlugRoute
  '/_public/case-studies/$slug': typeof PublicCaseStudiesSlugRoute
  '/_public/docs/$slug': typeof PublicDocsSlugRoute
  '/_public/legal/$doc': typeof PublicLegalDocRoute
  '/_public/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/_public/products/$slug': typeof PublicProductsSlugRoute
  '/_public/services/$slug': typeof PublicServicesSlugRoute
  '/_public/solutions/$industry': typeof PublicSolutionsIndustryRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/careers/': typeof PublicCareersIndexRoute
  '/_public/case-studies/': typeof PublicCaseStudiesIndexRoute
  '/_public/docs/': typeof PublicDocsIndexRoute
  '/_public/portfolio/': typeof PublicPortfolioIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/_public/solutions/': typeof PublicSolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-solutions'
    | '/clients'
    | '/contact'
    | '/domains'
    | '/downloads'
    | '/events'
    | '/faq'
    | '/hosting'
    | '/industries'
    | '/maintenance'
    | '/partners'
    | '/press'
    | '/pricing'
    | '/resources'
    | '/status'
    | '/support'
    | '/team'
    | '/technologies'
    | '/testimonials'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/docs/$slug'
    | '/legal/$doc'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/solutions/$industry'
    | '/blog/'
    | '/careers/'
    | '/case-studies/'
    | '/docs/'
    | '/portfolio/'
    | '/products/'
    | '/services/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/ai-solutions'
    | '/clients'
    | '/contact'
    | '/domains'
    | '/downloads'
    | '/events'
    | '/faq'
    | '/hosting'
    | '/industries'
    | '/maintenance'
    | '/partners'
    | '/press'
    | '/pricing'
    | '/resources'
    | '/status'
    | '/support'
    | '/team'
    | '/technologies'
    | '/testimonials'
    | '/'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/docs/$slug'
    | '/legal/$doc'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/solutions/$industry'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/docs'
    | '/portfolio'
    | '/products'
    | '/services'
    | '/solutions'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/ai-solutions'
    | '/_public/clients'
    | '/_public/contact'
    | '/_public/domains'
    | '/_public/downloads'
    | '/_public/events'
    | '/_public/faq'
    | '/_public/hosting'
    | '/_public/industries'
    | '/_public/maintenance'
    | '/_public/partners'
    | '/_public/press'
    | '/_public/pricing'
    | '/_public/resources'
    | '/_public/status'
    | '/_public/support'
    | '/_public/team'
    | '/_public/technologies'
    | '/_public/testimonials'
    | '/_public/'
    | '/_public/blog/$slug'
    | '/_public/careers/$slug'
    | '/_public/case-studies/$slug'
    | '/_public/docs/$slug'
    | '/_public/legal/$doc'
    | '/_public/portfolio/$slug'
    | '/_public/products/$slug'
    | '/_public/services/$slug'
    | '/_public/solutions/$industry'
    | '/_public/blog/'
    | '/_public/careers/'
    | '/_public/case-studies/'
    | '/_public/docs/'
    | '/_public/portfolio/'
    | '/_public/products/'
    | '/_public/services/'
    | '/_public/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/ai-solutions': {
      id: '/_public/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof PublicAiSolutionsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/clients': {
      id: '/_public/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof PublicClientsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/domains': {
      id: '/_public/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof PublicDomainsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/downloads': {
      id: '/_public/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof PublicDownloadsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/hosting': {
      id: '/_public/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof PublicHostingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/industries': {
      id: '/_public/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof PublicIndustriesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/maintenance': {
      id: '/_public/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof PublicMaintenanceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/partners': {
      id: '/_public/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PublicPartnersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/press': {
      id: '/_public/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PublicPressRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/resources': {
      id: '/_public/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/status': {
      id: '/_public/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof PublicStatusRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/support': {
      id: '/_public/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PublicSupportRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team': {
      id: '/_public/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof PublicTeamRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/technologies': {
      id: '/_public/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof PublicTechnologiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/testimonials': {
      id: '/_public/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof PublicTestimonialsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/careers/': {
      id: '/_public/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof PublicCareersIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/careers/$slug': {
      id: '/_public/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof PublicCareersSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/case-studies/': {
      id: '/_public/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof PublicCaseStudiesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/case-studies/$slug': {
      id: '/_public/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof PublicCaseStudiesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/': {
      id: '/_public/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof PublicDocsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/$slug': {
      id: '/_public/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof PublicDocsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/$doc': {
      id: '/_public/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof PublicLegalDocRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portfolio/': {
      id: '/_public/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PublicPortfolioIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portfolio/$slug': {
      id: '/_public/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PublicPortfolioSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/$slug': {
      id: '/_public/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof PublicProductsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/$slug': {
      id: '/_public/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof PublicServicesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/solutions/': {
      id: '/_public/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof PublicSolutionsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/solutions/$industry': {
      id: '/_public/solutions/$industry'
      path: '/solutions/$industry'
      fullPath: '/solutions/$industry'
      preLoaderRoute: typeof PublicSolutionsIndustryRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAiSolutionsRoute: typeof PublicAiSolutionsRoute
  PublicClientsRoute: typeof PublicClientsRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDomainsRoute: typeof PublicDomainsRoute
  PublicDownloadsRoute: typeof PublicDownloadsRoute
  PublicEventsRoute: typeof PublicEventsRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicHostingRoute: typeof PublicHostingRoute
  PublicIndustriesRoute: typeof PublicIndustriesRoute
  PublicMaintenanceRoute: typeof PublicMaintenanceRoute
  PublicPartnersRoute: typeof PublicPartnersRoute
  PublicPressRoute: typeof PublicPressRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicResourcesRoute: typeof PublicResourcesRoute
  PublicStatusRoute: typeof PublicStatusRoute
  PublicSupportRoute: typeof PublicSupportRoute
  PublicTeamRoute: typeof PublicTeamRoute
  PublicTechnologiesRoute: typeof PublicTechnologiesRoute
  PublicTestimonialsRoute: typeof PublicTestimonialsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicCareersSlugRoute: typeof PublicCareersSlugRoute
  PublicCaseStudiesSlugRoute: typeof PublicCaseStudiesSlugRoute
  PublicDocsSlugRoute: typeof PublicDocsSlugRoute
  PublicLegalDocRoute: typeof PublicLegalDocRoute
  PublicPortfolioSlugRoute: typeof PublicPortfolioSlugRoute
  PublicProductsSlugRoute: typeof PublicProductsSlugRoute
  PublicServicesSlugRoute: typeof PublicServicesSlugRoute
  PublicSolutionsIndustryRoute: typeof PublicSolutionsIndustryRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicCareersIndexRoute: typeof PublicCareersIndexRoute
  PublicCaseStudiesIndexRoute: typeof PublicCaseStudiesIndexRoute
  PublicDocsIndexRoute: typeof PublicDocsIndexRoute
  PublicPortfolioIndexRoute: typeof PublicPortfolioIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
  PublicSolutionsIndexRoute: typeof PublicSolutionsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAiSolutionsRoute: PublicAiSolutionsRoute,
  PublicClientsRoute: PublicClientsRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDomainsRoute: PublicDomainsRoute,
  PublicDownloadsRoute: PublicDownloadsRoute,
  PublicEventsRoute: PublicEventsRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicHostingRoute: PublicHostingRoute,
  PublicIndustriesRoute: PublicIndustriesRoute,
  PublicMaintenanceRoute: PublicMaintenanceRoute,
  PublicPartnersRoute: PublicPartnersRoute,
  PublicPressRoute: PublicPressRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicResourcesRoute: PublicResourcesRoute,
  PublicStatusRoute: PublicStatusRoute,
  PublicSupportRoute: PublicSupportRoute,
  PublicTeamRoute: PublicTeamRoute,
  PublicTechnologiesRoute: PublicTechnologiesRoute,
  PublicTestimonialsRoute: PublicTestimonialsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicCareersSlugRoute: PublicCareersSlugRoute,
  PublicCaseStudiesSlugRoute: PublicCaseStudiesSlugRoute,
  PublicDocsSlugRoute: PublicDocsSlugRoute,
  PublicLegalDocRoute: PublicLegalDocRoute,
  PublicPortfolioSlugRoute: PublicPortfolioSlugRoute,
  PublicProductsSlugRoute: PublicProductsSlugRoute,
  PublicServicesSlugRoute: PublicServicesSlugRoute,
  PublicSolutionsIndustryRoute: PublicSolutionsIndustryRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicCareersIndexRoute: PublicCareersIndexRoute,
  PublicCaseStudiesIndexRoute: PublicCaseStudiesIndexRoute,
  PublicDocsIndexRoute: PublicDocsIndexRoute,
  PublicPortfolioIndexRoute: PublicPortfolioIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
  PublicSolutionsIndexRoute: PublicSolutionsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
