/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicTestimonialsRouteImport } from './routes/_public.testimonials'
import { Route as PublicTechnologiesRouteImport } from './routes/_public.technologies'
import { Route as PublicTeamRouteImport } from './routes/_public.team'
import { Route as PublicSupportRouteImport } from './routes/_public.support'
import { Route as PublicStatusRouteImport } from './routes/_public.status'
import { Route as PublicResourcesRouteImport } from './routes/_public.resources'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as PublicPricingRouteImport } from './routes/_public.pricing'
import { Route as PublicPressRouteImport } from './routes/_public.press'
import { Route as PublicPartnersRouteImport } from './routes/_public.partners'
import { Route as PublicMaintenanceRouteImport } from './routes/_public.maintenance'
import { Route as PublicIndustriesRouteImport } from './routes/_public.industries'
import { Route as PublicHostingRouteImport } from './routes/_public.hosting'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as PublicDownloadsRouteImport } from './routes/_public.downloads'
import { Route as PublicDomainsRouteImport } from './routes/_public.domains'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicClientsRouteImport } from './routes/_public.clients'
import { Route as PublicAiSolutionsRouteImport } from './routes/_public.ai-solutions'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated.portal'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedBugsRouteImport } from './routes/_authenticated.bugs'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated.ai'
import { Route as PublicSolutionsIndexRouteImport } from './routes/_public.solutions.index'
import { Route as PublicServicesIndexRouteImport } from './routes/_public.services.index'
import { Route as PublicProductsIndexRouteImport } from './routes/_public.products.index'
import { Route as PublicPortfolioIndexRouteImport } from './routes/_public.portfolio.index'
import { Route as PublicDocsIndexRouteImport } from './routes/_public.docs.index'
import { Route as PublicCaseStudiesIndexRouteImport } from './routes/_public.case-studies.index'
import { Route as PublicCareersIndexRouteImport } from './routes/_public.careers.index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as AuthenticatedSupportIndexRouteImport } from './routes/_authenticated.support.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated.projects.index'
import { Route as AuthenticatedMarketingIndexRouteImport } from './routes/_authenticated.marketing.index'
import { Route as PublicSolutionsIndustryRouteImport } from './routes/_public.solutions.$industry'
import { Route as PublicServicesSlugRouteImport } from './routes/_public.services.$slug'
import { Route as PublicProductsSlugRouteImport } from './routes/_public.products.$slug'
import { Route as PublicPortfolioSlugRouteImport } from './routes/_public.portfolio.$slug'
import { Route as PublicLegalDocRouteImport } from './routes/_public.legal.$doc'
import { Route as PublicDocsSlugRouteImport } from './routes/_public.docs.$slug'
import { Route as PublicCaseStudiesSlugRouteImport } from './routes/_public.case-studies.$slug'
import { Route as PublicCareersSlugRouteImport } from './routes/_public.careers.$slug'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'
import { Route as AuthenticatedSupportWidgetRouteImport } from './routes/_authenticated.support.widget'
import { Route as AuthenticatedSupportSlaRouteImport } from './routes/_authenticated.support.sla'
import { Route as AuthenticatedSupportReportsRouteImport } from './routes/_authenticated.support.reports'
import { Route as AuthenticatedSupportQueueRouteImport } from './routes/_authenticated.support.queue'
import { Route as AuthenticatedSupportKnowledgeBaseRouteImport } from './routes/_authenticated.support.knowledge-base'
import { Route as AuthenticatedSupportInboxRouteImport } from './routes/_authenticated.support.inbox'
import { Route as AuthenticatedSupportDepartmentsRouteImport } from './routes/_authenticated.support.departments'
import { Route as AuthenticatedSupportDashboardRouteImport } from './routes/_authenticated.support.dashboard'
import { Route as AuthenticatedSupportChatHistoryRouteImport } from './routes/_authenticated.support.chat-history'
import { Route as AuthenticatedSupportCannedResponsesRouteImport } from './routes/_authenticated.support.canned-responses'
import { Route as AuthenticatedSupportAutomationRouteImport } from './routes/_authenticated.support.automation'
import { Route as AuthenticatedSupportAgentsRouteImport } from './routes/_authenticated.support.agents'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated.projects.$id'
import { Route as AuthenticatedMarketingPipelineRouteImport } from './routes/_authenticated.marketing.pipeline'
import { Route as AuthenticatedMarketingLandingRouteImport } from './routes/_authenticated.marketing.landing'
import { Route as AuthenticatedMarketingDashboardRouteImport } from './routes/_authenticated.marketing.dashboard'
import { Route as AuthenticatedMarketingContentRouteImport } from './routes/_authenticated.marketing.content'
import { Route as AuthenticatedMarketingCampaignsRouteImport } from './routes/_authenticated.marketing.campaigns'
import { Route as AuthenticatedMarketingActivityRouteImport } from './routes/_authenticated.marketing.activity'
import { Route as AuthenticatedMarketingAccountsRouteImport } from './routes/_authenticated.marketing.accounts'
import { Route as AuthenticatedHrPayrollRouteImport } from './routes/_authenticated.hr.payroll'
import { Route as AuthenticatedHrLeavesRouteImport } from './routes/_authenticated.hr.leaves'
import { Route as AuthenticatedHrEmployeesRouteImport } from './routes/_authenticated.hr.employees'
import { Route as AuthenticatedHrDepartmentsRouteImport } from './routes/_authenticated.hr.departments'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated.hr.attendance'
import { Route as AuthenticatedHostingSslRouteImport } from './routes/_authenticated.hosting.ssl'
import { Route as AuthenticatedHostingServersRouteImport } from './routes/_authenticated.hosting.servers'
import { Route as AuthenticatedHostingDomainsRouteImport } from './routes/_authenticated.hosting.domains'
import { Route as AuthenticatedHostingAccountsRouteImport } from './routes/_authenticated.hosting.accounts'
import { Route as AuthenticatedFinanceRevenueRouteImport } from './routes/_authenticated.finance.revenue'
import { Route as AuthenticatedFinancePaymentsRouteImport } from './routes/_authenticated.finance.payments'
import { Route as AuthenticatedFinanceInvoicesRouteImport } from './routes/_authenticated.finance.invoices'
import { Route as AuthenticatedFinanceExpensesRouteImport } from './routes/_authenticated.finance.expenses'
import { Route as AuthenticatedCrmQuotationsRouteImport } from './routes/_authenticated.crm.quotations'
import { Route as AuthenticatedCrmMeetingsRouteImport } from './routes/_authenticated.crm.meetings'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated.crm.leads'
import { Route as AuthenticatedCrmContractsRouteImport } from './routes/_authenticated.crm.contracts'
import { Route as AuthenticatedCrmContactsRouteImport } from './routes/_authenticated.crm.contacts'
import { Route as AuthenticatedCrmCompaniesRouteImport } from './routes/_authenticated.crm.companies'
import { Route as AuthenticatedCrmClientsRouteImport } from './routes/_authenticated.crm.clients'
import { Route as AuthenticatedSupportTicketsIndexRouteImport } from './routes/_authenticated.support.tickets.index'
import { Route as AuthenticatedSupportTicketsIdRouteImport } from './routes/_authenticated.support.tickets.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTestimonialsRoute = PublicTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTechnologiesRoute = PublicTechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTeamRoute = PublicTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSupportRoute = PublicSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStatusRoute = PublicStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResourcesRoute = PublicResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPressRoute = PublicPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPartnersRoute = PublicPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMaintenanceRoute = PublicMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => PublicRoute,
} as any)
const PublicIndustriesRoute = PublicIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHostingRoute = PublicHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDownloadsRoute = PublicDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDomainsRoute = PublicDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicClientsRoute = PublicClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAiSolutionsRoute = PublicAiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBugsRoute = AuthenticatedBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicSolutionsIndexRoute = PublicSolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortfolioIndexRoute = PublicPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsIndexRoute = PublicDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCaseStudiesIndexRoute = PublicCaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCareersIndexRoute = PublicCareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedSupportIndexRoute =
  AuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingIndexRoute =
  AuthenticatedMarketingIndexRouteImport.update({
    id: '/marketing/',
    path: '/marketing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicSolutionsIndustryRoute = PublicSolutionsIndustryRouteImport.update({
  id: '/solutions/$industry',
  path: '/solutions/$industry',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesSlugRoute = PublicServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsSlugRoute = PublicProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPortfolioSlugRoute = PublicPortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLegalDocRoute = PublicLegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDocsSlugRoute = PublicDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCaseStudiesSlugRoute = PublicCaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCareersSlugRoute = PublicCareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedSupportWidgetRoute =
  AuthenticatedSupportWidgetRouteImport.update({
    id: '/support/widget',
    path: '/support/widget',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportSlaRoute = AuthenticatedSupportSlaRouteImport.update({
  id: '/support/sla',
  path: '/support/sla',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportReportsRoute =
  AuthenticatedSupportReportsRouteImport.update({
    id: '/support/reports',
    path: '/support/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportQueueRoute =
  AuthenticatedSupportQueueRouteImport.update({
    id: '/support/queue',
    path: '/support/queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportKnowledgeBaseRoute =
  AuthenticatedSupportKnowledgeBaseRouteImport.update({
    id: '/support/knowledge-base',
    path: '/support/knowledge-base',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportInboxRoute =
  AuthenticatedSupportInboxRouteImport.update({
    id: '/support/inbox',
    path: '/support/inbox',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportDepartmentsRoute =
  AuthenticatedSupportDepartmentsRouteImport.update({
    id: '/support/departments',
    path: '/support/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportDashboardRoute =
  AuthenticatedSupportDashboardRouteImport.update({
    id: '/support/dashboard',
    path: '/support/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportChatHistoryRoute =
  AuthenticatedSupportChatHistoryRouteImport.update({
    id: '/support/chat-history',
    path: '/support/chat-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportCannedResponsesRoute =
  AuthenticatedSupportCannedResponsesRouteImport.update({
    id: '/support/canned-responses',
    path: '/support/canned-responses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportAutomationRoute =
  AuthenticatedSupportAutomationRouteImport.update({
    id: '/support/automation',
    path: '/support/automation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportAgentsRoute =
  AuthenticatedSupportAgentsRouteImport.update({
    id: '/support/agents',
    path: '/support/agents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingPipelineRoute =
  AuthenticatedMarketingPipelineRouteImport.update({
    id: '/marketing/pipeline',
    path: '/marketing/pipeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingLandingRoute =
  AuthenticatedMarketingLandingRouteImport.update({
    id: '/marketing/landing',
    path: '/marketing/landing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingDashboardRoute =
  AuthenticatedMarketingDashboardRouteImport.update({
    id: '/marketing/dashboard',
    path: '/marketing/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingContentRoute =
  AuthenticatedMarketingContentRouteImport.update({
    id: '/marketing/content',
    path: '/marketing/content',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingCampaignsRoute =
  AuthenticatedMarketingCampaignsRouteImport.update({
    id: '/marketing/campaigns',
    path: '/marketing/campaigns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingActivityRoute =
  AuthenticatedMarketingActivityRouteImport.update({
    id: '/marketing/activity',
    path: '/marketing/activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingAccountsRoute =
  AuthenticatedMarketingAccountsRouteImport.update({
    id: '/marketing/accounts',
    path: '/marketing/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrPayrollRoute = AuthenticatedHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrLeavesRoute = AuthenticatedHrLeavesRouteImport.update({
  id: '/hr/leaves',
  path: '/hr/leaves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrEmployeesRoute =
  AuthenticatedHrEmployeesRouteImport.update({
    id: '/hr/employees',
    path: '/hr/employees',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrDepartmentsRoute =
  AuthenticatedHrDepartmentsRouteImport.update({
    id: '/hr/departments',
    path: '/hr/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostingSslRoute = AuthenticatedHostingSslRouteImport.update({
  id: '/hosting/ssl',
  path: '/hosting/ssl',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostingServersRoute =
  AuthenticatedHostingServersRouteImport.update({
    id: '/hosting/servers',
    path: '/hosting/servers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostingDomainsRoute =
  AuthenticatedHostingDomainsRouteImport.update({
    id: '/hosting/domains',
    path: '/hosting/domains',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostingAccountsRoute =
  AuthenticatedHostingAccountsRouteImport.update({
    id: '/hosting/accounts',
    path: '/hosting/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRevenueRoute =
  AuthenticatedFinanceRevenueRouteImport.update({
    id: '/finance/revenue',
    path: '/finance/revenue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancePaymentsRoute =
  AuthenticatedFinancePaymentsRouteImport.update({
    id: '/finance/payments',
    path: '/finance/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceInvoicesRoute =
  AuthenticatedFinanceInvoicesRouteImport.update({
    id: '/finance/invoices',
    path: '/finance/invoices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceExpensesRoute =
  AuthenticatedFinanceExpensesRouteImport.update({
    id: '/finance/expenses',
    path: '/finance/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmQuotationsRoute =
  AuthenticatedCrmQuotationsRouteImport.update({
    id: '/crm/quotations',
    path: '/crm/quotations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmMeetingsRoute =
  AuthenticatedCrmMeetingsRouteImport.update({
    id: '/crm/meetings',
    path: '/crm/meetings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmContractsRoute =
  AuthenticatedCrmContractsRouteImport.update({
    id: '/crm/contracts',
    path: '/crm/contracts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmContactsRoute =
  AuthenticatedCrmContactsRouteImport.update({
    id: '/crm/contacts',
    path: '/crm/contacts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmCompaniesRoute =
  AuthenticatedCrmCompaniesRouteImport.update({
    id: '/crm/companies',
    path: '/crm/companies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCrmClientsRoute = AuthenticatedCrmClientsRouteImport.update({
  id: '/crm/clients',
  path: '/crm/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportTicketsIndexRoute =
  AuthenticatedSupportTicketsIndexRouteImport.update({
    id: '/support/tickets/',
    path: '/support/tickets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportTicketsIdRoute =
  AuthenticatedSupportTicketsIdRouteImport.update({
    id: '/support/tickets/$id',
    path: '/support/tickets/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AuthenticatedAiRoute
  '/bugs': typeof AuthenticatedBugsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/about': typeof PublicAboutRoute
  '/ai-solutions': typeof PublicAiSolutionsRoute
  '/clients': typeof PublicClientsRoute
  '/contact': typeof PublicContactRoute
  '/domains': typeof PublicDomainsRoute
  '/downloads': typeof PublicDownloadsRoute
  '/events': typeof PublicEventsRoute
  '/faq': typeof PublicFaqRoute
  '/hosting': typeof PublicHostingRoute
  '/industries': typeof PublicIndustriesRoute
  '/maintenance': typeof PublicMaintenanceRoute
  '/partners': typeof PublicPartnersRoute
  '/press': typeof PublicPressRoute
  '/pricing': typeof PublicPricingRoute
  '/register': typeof PublicRegisterRoute
  '/resources': typeof PublicResourcesRoute
  '/status': typeof PublicStatusRoute
  '/support': typeof PublicSupportRoute
  '/team': typeof PublicTeamRoute
  '/technologies': typeof PublicTechnologiesRoute
  '/testimonials': typeof PublicTestimonialsRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/companies': typeof AuthenticatedCrmCompaniesRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/crm/contracts': typeof AuthenticatedCrmContractsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/meetings': typeof AuthenticatedCrmMeetingsRoute
  '/crm/quotations': typeof AuthenticatedCrmQuotationsRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/payments': typeof AuthenticatedFinancePaymentsRoute
  '/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/hosting/accounts': typeof AuthenticatedHostingAccountsRoute
  '/hosting/domains': typeof AuthenticatedHostingDomainsRoute
  '/hosting/servers': typeof AuthenticatedHostingServersRoute
  '/hosting/ssl': typeof AuthenticatedHostingSslRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/departments': typeof AuthenticatedHrDepartmentsRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/marketing/accounts': typeof AuthenticatedMarketingAccountsRoute
  '/marketing/activity': typeof AuthenticatedMarketingActivityRoute
  '/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/marketing/content': typeof AuthenticatedMarketingContentRoute
  '/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/marketing/landing': typeof AuthenticatedMarketingLandingRoute
  '/marketing/pipeline': typeof AuthenticatedMarketingPipelineRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/support/agents': typeof AuthenticatedSupportAgentsRoute
  '/support/automation': typeof AuthenticatedSupportAutomationRoute
  '/support/canned-responses': typeof AuthenticatedSupportCannedResponsesRoute
  '/support/chat-history': typeof AuthenticatedSupportChatHistoryRoute
  '/support/dashboard': typeof AuthenticatedSupportDashboardRoute
  '/support/departments': typeof AuthenticatedSupportDepartmentsRoute
  '/support/inbox': typeof AuthenticatedSupportInboxRoute
  '/support/knowledge-base': typeof AuthenticatedSupportKnowledgeBaseRoute
  '/support/queue': typeof AuthenticatedSupportQueueRoute
  '/support/reports': typeof AuthenticatedSupportReportsRoute
  '/support/sla': typeof AuthenticatedSupportSlaRoute
  '/support/widget': typeof AuthenticatedSupportWidgetRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/careers/$slug': typeof PublicCareersSlugRoute
  '/case-studies/$slug': typeof PublicCaseStudiesSlugRoute
  '/docs/$slug': typeof PublicDocsSlugRoute
  '/legal/$doc': typeof PublicLegalDocRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/solutions/$industry': typeof PublicSolutionsIndustryRoute
  '/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/support/': typeof AuthenticatedSupportIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/careers/': typeof PublicCareersIndexRoute
  '/case-studies/': typeof PublicCaseStudiesIndexRoute
  '/docs/': typeof PublicDocsIndexRoute
  '/portfolio/': typeof PublicPortfolioIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/services/': typeof PublicServicesIndexRoute
  '/solutions/': typeof PublicSolutionsIndexRoute
  '/support/tickets/$id': typeof AuthenticatedSupportTicketsIdRoute
  '/support/tickets/': typeof AuthenticatedSupportTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AuthenticatedAiRoute
  '/bugs': typeof AuthenticatedBugsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/about': typeof PublicAboutRoute
  '/ai-solutions': typeof PublicAiSolutionsRoute
  '/clients': typeof PublicClientsRoute
  '/contact': typeof PublicContactRoute
  '/domains': typeof PublicDomainsRoute
  '/downloads': typeof PublicDownloadsRoute
  '/events': typeof PublicEventsRoute
  '/faq': typeof PublicFaqRoute
  '/hosting': typeof PublicHostingRoute
  '/industries': typeof PublicIndustriesRoute
  '/maintenance': typeof PublicMaintenanceRoute
  '/partners': typeof PublicPartnersRoute
  '/press': typeof PublicPressRoute
  '/pricing': typeof PublicPricingRoute
  '/register': typeof PublicRegisterRoute
  '/resources': typeof PublicResourcesRoute
  '/status': typeof PublicStatusRoute
  '/support': typeof AuthenticatedSupportIndexRoute
  '/team': typeof PublicTeamRoute
  '/technologies': typeof PublicTechnologiesRoute
  '/testimonials': typeof PublicTestimonialsRoute
  '/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/crm/companies': typeof AuthenticatedCrmCompaniesRoute
  '/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/crm/contracts': typeof AuthenticatedCrmContractsRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/meetings': typeof AuthenticatedCrmMeetingsRoute
  '/crm/quotations': typeof AuthenticatedCrmQuotationsRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/finance/payments': typeof AuthenticatedFinancePaymentsRoute
  '/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/hosting/accounts': typeof AuthenticatedHostingAccountsRoute
  '/hosting/domains': typeof AuthenticatedHostingDomainsRoute
  '/hosting/servers': typeof AuthenticatedHostingServersRoute
  '/hosting/ssl': typeof AuthenticatedHostingSslRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/departments': typeof AuthenticatedHrDepartmentsRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/marketing/accounts': typeof AuthenticatedMarketingAccountsRoute
  '/marketing/activity': typeof AuthenticatedMarketingActivityRoute
  '/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/marketing/content': typeof AuthenticatedMarketingContentRoute
  '/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/marketing/landing': typeof AuthenticatedMarketingLandingRoute
  '/marketing/pipeline': typeof AuthenticatedMarketingPipelineRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/support/agents': typeof AuthenticatedSupportAgentsRoute
  '/support/automation': typeof AuthenticatedSupportAutomationRoute
  '/support/canned-responses': typeof AuthenticatedSupportCannedResponsesRoute
  '/support/chat-history': typeof AuthenticatedSupportChatHistoryRoute
  '/support/dashboard': typeof AuthenticatedSupportDashboardRoute
  '/support/departments': typeof AuthenticatedSupportDepartmentsRoute
  '/support/inbox': typeof AuthenticatedSupportInboxRoute
  '/support/knowledge-base': typeof AuthenticatedSupportKnowledgeBaseRoute
  '/support/queue': typeof AuthenticatedSupportQueueRoute
  '/support/reports': typeof AuthenticatedSupportReportsRoute
  '/support/sla': typeof AuthenticatedSupportSlaRoute
  '/support/widget': typeof AuthenticatedSupportWidgetRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/careers/$slug': typeof PublicCareersSlugRoute
  '/case-studies/$slug': typeof PublicCaseStudiesSlugRoute
  '/docs/$slug': typeof PublicDocsSlugRoute
  '/legal/$doc': typeof PublicLegalDocRoute
  '/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/products/$slug': typeof PublicProductsSlugRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/solutions/$industry': typeof PublicSolutionsIndustryRoute
  '/marketing': typeof AuthenticatedMarketingIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/careers': typeof PublicCareersIndexRoute
  '/case-studies': typeof PublicCaseStudiesIndexRoute
  '/docs': typeof PublicDocsIndexRoute
  '/portfolio': typeof PublicPortfolioIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/services': typeof PublicServicesIndexRoute
  '/solutions': typeof PublicSolutionsIndexRoute
  '/support/tickets/$id': typeof AuthenticatedSupportTicketsIdRoute
  '/support/tickets': typeof AuthenticatedSupportTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/bugs': typeof AuthenticatedBugsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/ai-solutions': typeof PublicAiSolutionsRoute
  '/_public/clients': typeof PublicClientsRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/domains': typeof PublicDomainsRoute
  '/_public/downloads': typeof PublicDownloadsRoute
  '/_public/events': typeof PublicEventsRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/hosting': typeof PublicHostingRoute
  '/_public/industries': typeof PublicIndustriesRoute
  '/_public/maintenance': typeof PublicMaintenanceRoute
  '/_public/partners': typeof PublicPartnersRoute
  '/_public/press': typeof PublicPressRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/resources': typeof PublicResourcesRoute
  '/_public/status': typeof PublicStatusRoute
  '/_public/support': typeof PublicSupportRoute
  '/_public/team': typeof PublicTeamRoute
  '/_public/technologies': typeof PublicTechnologiesRoute
  '/_public/testimonials': typeof PublicTestimonialsRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/crm/clients': typeof AuthenticatedCrmClientsRoute
  '/_authenticated/crm/companies': typeof AuthenticatedCrmCompaniesRoute
  '/_authenticated/crm/contacts': typeof AuthenticatedCrmContactsRoute
  '/_authenticated/crm/contracts': typeof AuthenticatedCrmContractsRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/crm/meetings': typeof AuthenticatedCrmMeetingsRoute
  '/_authenticated/crm/quotations': typeof AuthenticatedCrmQuotationsRoute
  '/_authenticated/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/_authenticated/finance/invoices': typeof AuthenticatedFinanceInvoicesRoute
  '/_authenticated/finance/payments': typeof AuthenticatedFinancePaymentsRoute
  '/_authenticated/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/_authenticated/hosting/accounts': typeof AuthenticatedHostingAccountsRoute
  '/_authenticated/hosting/domains': typeof AuthenticatedHostingDomainsRoute
  '/_authenticated/hosting/servers': typeof AuthenticatedHostingServersRoute
  '/_authenticated/hosting/ssl': typeof AuthenticatedHostingSslRoute
  '/_authenticated/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr/departments': typeof AuthenticatedHrDepartmentsRoute
  '/_authenticated/hr/employees': typeof AuthenticatedHrEmployeesRoute
  '/_authenticated/hr/leaves': typeof AuthenticatedHrLeavesRoute
  '/_authenticated/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/_authenticated/marketing/accounts': typeof AuthenticatedMarketingAccountsRoute
  '/_authenticated/marketing/activity': typeof AuthenticatedMarketingActivityRoute
  '/_authenticated/marketing/campaigns': typeof AuthenticatedMarketingCampaignsRoute
  '/_authenticated/marketing/content': typeof AuthenticatedMarketingContentRoute
  '/_authenticated/marketing/dashboard': typeof AuthenticatedMarketingDashboardRoute
  '/_authenticated/marketing/landing': typeof AuthenticatedMarketingLandingRoute
  '/_authenticated/marketing/pipeline': typeof AuthenticatedMarketingPipelineRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/support/agents': typeof AuthenticatedSupportAgentsRoute
  '/_authenticated/support/automation': typeof AuthenticatedSupportAutomationRoute
  '/_authenticated/support/canned-responses': typeof AuthenticatedSupportCannedResponsesRoute
  '/_authenticated/support/chat-history': typeof AuthenticatedSupportChatHistoryRoute
  '/_authenticated/support/dashboard': typeof AuthenticatedSupportDashboardRoute
  '/_authenticated/support/departments': typeof AuthenticatedSupportDepartmentsRoute
  '/_authenticated/support/inbox': typeof AuthenticatedSupportInboxRoute
  '/_authenticated/support/knowledge-base': typeof AuthenticatedSupportKnowledgeBaseRoute
  '/_authenticated/support/queue': typeof AuthenticatedSupportQueueRoute
  '/_authenticated/support/reports': typeof AuthenticatedSupportReportsRoute
  '/_authenticated/support/sla': typeof AuthenticatedSupportSlaRoute
  '/_authenticated/support/widget': typeof AuthenticatedSupportWidgetRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/careers/$slug': typeof PublicCareersSlugRoute
  '/_public/case-studies/$slug': typeof PublicCaseStudiesSlugRoute
  '/_public/docs/$slug': typeof PublicDocsSlugRoute
  '/_public/legal/$doc': typeof PublicLegalDocRoute
  '/_public/portfolio/$slug': typeof PublicPortfolioSlugRoute
  '/_public/products/$slug': typeof PublicProductsSlugRoute
  '/_public/services/$slug': typeof PublicServicesSlugRoute
  '/_public/solutions/$industry': typeof PublicSolutionsIndustryRoute
  '/_authenticated/marketing/': typeof AuthenticatedMarketingIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/support/': typeof AuthenticatedSupportIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/careers/': typeof PublicCareersIndexRoute
  '/_public/case-studies/': typeof PublicCaseStudiesIndexRoute
  '/_public/docs/': typeof PublicDocsIndexRoute
  '/_public/portfolio/': typeof PublicPortfolioIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
  '/_public/solutions/': typeof PublicSolutionsIndexRoute
  '/_authenticated/support/tickets/$id': typeof AuthenticatedSupportTicketsIdRoute
  '/_authenticated/support/tickets/': typeof AuthenticatedSupportTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/ai'
    | '/bugs'
    | '/dashboard'
    | '/notifications'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/about'
    | '/ai-solutions'
    | '/clients'
    | '/contact'
    | '/domains'
    | '/downloads'
    | '/events'
    | '/faq'
    | '/hosting'
    | '/industries'
    | '/maintenance'
    | '/partners'
    | '/press'
    | '/pricing'
    | '/register'
    | '/resources'
    | '/status'
    | '/support'
    | '/team'
    | '/technologies'
    | '/testimonials'
    | '/crm/clients'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/contracts'
    | '/crm/leads'
    | '/crm/meetings'
    | '/crm/quotations'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/revenue'
    | '/hosting/accounts'
    | '/hosting/domains'
    | '/hosting/servers'
    | '/hosting/ssl'
    | '/hr/attendance'
    | '/hr/departments'
    | '/hr/employees'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/marketing/accounts'
    | '/marketing/activity'
    | '/marketing/campaigns'
    | '/marketing/content'
    | '/marketing/dashboard'
    | '/marketing/landing'
    | '/marketing/pipeline'
    | '/projects/$id'
    | '/support/agents'
    | '/support/automation'
    | '/support/canned-responses'
    | '/support/chat-history'
    | '/support/dashboard'
    | '/support/departments'
    | '/support/inbox'
    | '/support/knowledge-base'
    | '/support/queue'
    | '/support/reports'
    | '/support/sla'
    | '/support/widget'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/docs/$slug'
    | '/legal/$doc'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/solutions/$industry'
    | '/marketing/'
    | '/projects/'
    | '/support/'
    | '/blog/'
    | '/careers/'
    | '/case-studies/'
    | '/docs/'
    | '/portfolio/'
    | '/products/'
    | '/services/'
    | '/solutions/'
    | '/support/tickets/$id'
    | '/support/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/ai'
    | '/bugs'
    | '/dashboard'
    | '/notifications'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/about'
    | '/ai-solutions'
    | '/clients'
    | '/contact'
    | '/domains'
    | '/downloads'
    | '/events'
    | '/faq'
    | '/hosting'
    | '/industries'
    | '/maintenance'
    | '/partners'
    | '/press'
    | '/pricing'
    | '/register'
    | '/resources'
    | '/status'
    | '/support'
    | '/team'
    | '/technologies'
    | '/testimonials'
    | '/crm/clients'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/contracts'
    | '/crm/leads'
    | '/crm/meetings'
    | '/crm/quotations'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/revenue'
    | '/hosting/accounts'
    | '/hosting/domains'
    | '/hosting/servers'
    | '/hosting/ssl'
    | '/hr/attendance'
    | '/hr/departments'
    | '/hr/employees'
    | '/hr/leaves'
    | '/hr/payroll'
    | '/marketing/accounts'
    | '/marketing/activity'
    | '/marketing/campaigns'
    | '/marketing/content'
    | '/marketing/dashboard'
    | '/marketing/landing'
    | '/marketing/pipeline'
    | '/projects/$id'
    | '/support/agents'
    | '/support/automation'
    | '/support/canned-responses'
    | '/support/chat-history'
    | '/support/dashboard'
    | '/support/departments'
    | '/support/inbox'
    | '/support/knowledge-base'
    | '/support/queue'
    | '/support/reports'
    | '/support/sla'
    | '/support/widget'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/docs/$slug'
    | '/legal/$doc'
    | '/portfolio/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/solutions/$industry'
    | '/marketing'
    | '/projects'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/docs'
    | '/portfolio'
    | '/products'
    | '/services'
    | '/solutions'
    | '/support/tickets/$id'
    | '/support/tickets'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/ai'
    | '/_authenticated/bugs'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/portal'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_public/about'
    | '/_public/ai-solutions'
    | '/_public/clients'
    | '/_public/contact'
    | '/_public/domains'
    | '/_public/downloads'
    | '/_public/events'
    | '/_public/faq'
    | '/_public/hosting'
    | '/_public/industries'
    | '/_public/maintenance'
    | '/_public/partners'
    | '/_public/press'
    | '/_public/pricing'
    | '/_public/register'
    | '/_public/resources'
    | '/_public/status'
    | '/_public/support'
    | '/_public/team'
    | '/_public/technologies'
    | '/_public/testimonials'
    | '/_public/'
    | '/_authenticated/crm/clients'
    | '/_authenticated/crm/companies'
    | '/_authenticated/crm/contacts'
    | '/_authenticated/crm/contracts'
    | '/_authenticated/crm/leads'
    | '/_authenticated/crm/meetings'
    | '/_authenticated/crm/quotations'
    | '/_authenticated/finance/expenses'
    | '/_authenticated/finance/invoices'
    | '/_authenticated/finance/payments'
    | '/_authenticated/finance/revenue'
    | '/_authenticated/hosting/accounts'
    | '/_authenticated/hosting/domains'
    | '/_authenticated/hosting/servers'
    | '/_authenticated/hosting/ssl'
    | '/_authenticated/hr/attendance'
    | '/_authenticated/hr/departments'
    | '/_authenticated/hr/employees'
    | '/_authenticated/hr/leaves'
    | '/_authenticated/hr/payroll'
    | '/_authenticated/marketing/accounts'
    | '/_authenticated/marketing/activity'
    | '/_authenticated/marketing/campaigns'
    | '/_authenticated/marketing/content'
    | '/_authenticated/marketing/dashboard'
    | '/_authenticated/marketing/landing'
    | '/_authenticated/marketing/pipeline'
    | '/_authenticated/projects/$id'
    | '/_authenticated/support/agents'
    | '/_authenticated/support/automation'
    | '/_authenticated/support/canned-responses'
    | '/_authenticated/support/chat-history'
    | '/_authenticated/support/dashboard'
    | '/_authenticated/support/departments'
    | '/_authenticated/support/inbox'
    | '/_authenticated/support/knowledge-base'
    | '/_authenticated/support/queue'
    | '/_authenticated/support/reports'
    | '/_authenticated/support/sla'
    | '/_authenticated/support/widget'
    | '/_public/blog/$slug'
    | '/_public/careers/$slug'
    | '/_public/case-studies/$slug'
    | '/_public/docs/$slug'
    | '/_public/legal/$doc'
    | '/_public/portfolio/$slug'
    | '/_public/products/$slug'
    | '/_public/services/$slug'
    | '/_public/solutions/$industry'
    | '/_authenticated/marketing/'
    | '/_authenticated/projects/'
    | '/_authenticated/support/'
    | '/_public/blog/'
    | '/_public/careers/'
    | '/_public/case-studies/'
    | '/_public/docs/'
    | '/_public/portfolio/'
    | '/_public/products/'
    | '/_public/services/'
    | '/_public/solutions/'
    | '/_authenticated/support/tickets/$id'
    | '/_authenticated/support/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/testimonials': {
      id: '/_public/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof PublicTestimonialsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/technologies': {
      id: '/_public/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof PublicTechnologiesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/team': {
      id: '/_public/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof PublicTeamRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/support': {
      id: '/_public/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PublicSupportRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/status': {
      id: '/_public/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof PublicStatusRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/resources': {
      id: '/_public/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof PublicResourcesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/press': {
      id: '/_public/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PublicPressRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/partners': {
      id: '/_public/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PublicPartnersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/maintenance': {
      id: '/_public/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof PublicMaintenanceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/industries': {
      id: '/_public/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof PublicIndustriesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/hosting': {
      id: '/_public/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof PublicHostingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/downloads': {
      id: '/_public/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof PublicDownloadsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/domains': {
      id: '/_public/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof PublicDomainsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/clients': {
      id: '/_public/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof PublicClientsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/ai-solutions': {
      id: '/_public/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/ai-solutions'
      preLoaderRoute: typeof PublicAiSolutionsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bugs': {
      id: '/_authenticated/bugs'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof AuthenticatedBugsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/solutions/': {
      id: '/_public/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof PublicSolutionsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portfolio/': {
      id: '/_public/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PublicPortfolioIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/': {
      id: '/_public/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof PublicDocsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/case-studies/': {
      id: '/_public/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof PublicCaseStudiesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/careers/': {
      id: '/_public/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof PublicCareersIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/support/': {
      id: '/_authenticated/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthenticatedSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/': {
      id: '/_authenticated/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AuthenticatedMarketingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/solutions/$industry': {
      id: '/_public/solutions/$industry'
      path: '/solutions/$industry'
      fullPath: '/solutions/$industry'
      preLoaderRoute: typeof PublicSolutionsIndustryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/$slug': {
      id: '/_public/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof PublicServicesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/$slug': {
      id: '/_public/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof PublicProductsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/portfolio/$slug': {
      id: '/_public/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PublicPortfolioSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/legal/$doc': {
      id: '/_public/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof PublicLegalDocRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/docs/$slug': {
      id: '/_public/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof PublicDocsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/case-studies/$slug': {
      id: '/_public/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof PublicCaseStudiesSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/careers/$slug': {
      id: '/_public/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof PublicCareersSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/support/widget': {
      id: '/_authenticated/support/widget'
      path: '/support/widget'
      fullPath: '/support/widget'
      preLoaderRoute: typeof AuthenticatedSupportWidgetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/sla': {
      id: '/_authenticated/support/sla'
      path: '/support/sla'
      fullPath: '/support/sla'
      preLoaderRoute: typeof AuthenticatedSupportSlaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/reports': {
      id: '/_authenticated/support/reports'
      path: '/support/reports'
      fullPath: '/support/reports'
      preLoaderRoute: typeof AuthenticatedSupportReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/queue': {
      id: '/_authenticated/support/queue'
      path: '/support/queue'
      fullPath: '/support/queue'
      preLoaderRoute: typeof AuthenticatedSupportQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/knowledge-base': {
      id: '/_authenticated/support/knowledge-base'
      path: '/support/knowledge-base'
      fullPath: '/support/knowledge-base'
      preLoaderRoute: typeof AuthenticatedSupportKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/inbox': {
      id: '/_authenticated/support/inbox'
      path: '/support/inbox'
      fullPath: '/support/inbox'
      preLoaderRoute: typeof AuthenticatedSupportInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/departments': {
      id: '/_authenticated/support/departments'
      path: '/support/departments'
      fullPath: '/support/departments'
      preLoaderRoute: typeof AuthenticatedSupportDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/dashboard': {
      id: '/_authenticated/support/dashboard'
      path: '/support/dashboard'
      fullPath: '/support/dashboard'
      preLoaderRoute: typeof AuthenticatedSupportDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/chat-history': {
      id: '/_authenticated/support/chat-history'
      path: '/support/chat-history'
      fullPath: '/support/chat-history'
      preLoaderRoute: typeof AuthenticatedSupportChatHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/canned-responses': {
      id: '/_authenticated/support/canned-responses'
      path: '/support/canned-responses'
      fullPath: '/support/canned-responses'
      preLoaderRoute: typeof AuthenticatedSupportCannedResponsesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/automation': {
      id: '/_authenticated/support/automation'
      path: '/support/automation'
      fullPath: '/support/automation'
      preLoaderRoute: typeof AuthenticatedSupportAutomationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/agents': {
      id: '/_authenticated/support/agents'
      path: '/support/agents'
      fullPath: '/support/agents'
      preLoaderRoute: typeof AuthenticatedSupportAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/pipeline': {
      id: '/_authenticated/marketing/pipeline'
      path: '/marketing/pipeline'
      fullPath: '/marketing/pipeline'
      preLoaderRoute: typeof AuthenticatedMarketingPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/landing': {
      id: '/_authenticated/marketing/landing'
      path: '/marketing/landing'
      fullPath: '/marketing/landing'
      preLoaderRoute: typeof AuthenticatedMarketingLandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/dashboard': {
      id: '/_authenticated/marketing/dashboard'
      path: '/marketing/dashboard'
      fullPath: '/marketing/dashboard'
      preLoaderRoute: typeof AuthenticatedMarketingDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/content': {
      id: '/_authenticated/marketing/content'
      path: '/marketing/content'
      fullPath: '/marketing/content'
      preLoaderRoute: typeof AuthenticatedMarketingContentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/campaigns': {
      id: '/_authenticated/marketing/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof AuthenticatedMarketingCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/activity': {
      id: '/_authenticated/marketing/activity'
      path: '/marketing/activity'
      fullPath: '/marketing/activity'
      preLoaderRoute: typeof AuthenticatedMarketingActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing/accounts': {
      id: '/_authenticated/marketing/accounts'
      path: '/marketing/accounts'
      fullPath: '/marketing/accounts'
      preLoaderRoute: typeof AuthenticatedMarketingAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/payroll': {
      id: '/_authenticated/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AuthenticatedHrPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/leaves': {
      id: '/_authenticated/hr/leaves'
      path: '/hr/leaves'
      fullPath: '/hr/leaves'
      preLoaderRoute: typeof AuthenticatedHrLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/employees': {
      id: '/_authenticated/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AuthenticatedHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/departments': {
      id: '/_authenticated/hr/departments'
      path: '/hr/departments'
      fullPath: '/hr/departments'
      preLoaderRoute: typeof AuthenticatedHrDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/attendance': {
      id: '/_authenticated/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosting/ssl': {
      id: '/_authenticated/hosting/ssl'
      path: '/hosting/ssl'
      fullPath: '/hosting/ssl'
      preLoaderRoute: typeof AuthenticatedHostingSslRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosting/servers': {
      id: '/_authenticated/hosting/servers'
      path: '/hosting/servers'
      fullPath: '/hosting/servers'
      preLoaderRoute: typeof AuthenticatedHostingServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosting/domains': {
      id: '/_authenticated/hosting/domains'
      path: '/hosting/domains'
      fullPath: '/hosting/domains'
      preLoaderRoute: typeof AuthenticatedHostingDomainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosting/accounts': {
      id: '/_authenticated/hosting/accounts'
      path: '/hosting/accounts'
      fullPath: '/hosting/accounts'
      preLoaderRoute: typeof AuthenticatedHostingAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/revenue': {
      id: '/_authenticated/finance/revenue'
      path: '/finance/revenue'
      fullPath: '/finance/revenue'
      preLoaderRoute: typeof AuthenticatedFinanceRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/payments': {
      id: '/_authenticated/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof AuthenticatedFinancePaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/invoices': {
      id: '/_authenticated/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AuthenticatedFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/expenses': {
      id: '/_authenticated/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AuthenticatedFinanceExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/quotations': {
      id: '/_authenticated/crm/quotations'
      path: '/crm/quotations'
      fullPath: '/crm/quotations'
      preLoaderRoute: typeof AuthenticatedCrmQuotationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/meetings': {
      id: '/_authenticated/crm/meetings'
      path: '/crm/meetings'
      fullPath: '/crm/meetings'
      preLoaderRoute: typeof AuthenticatedCrmMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/contracts': {
      id: '/_authenticated/crm/contracts'
      path: '/crm/contracts'
      fullPath: '/crm/contracts'
      preLoaderRoute: typeof AuthenticatedCrmContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/contacts': {
      id: '/_authenticated/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof AuthenticatedCrmContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/companies': {
      id: '/_authenticated/crm/companies'
      path: '/crm/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof AuthenticatedCrmCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm/clients': {
      id: '/_authenticated/crm/clients'
      path: '/crm/clients'
      fullPath: '/crm/clients'
      preLoaderRoute: typeof AuthenticatedCrmClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/tickets/': {
      id: '/_authenticated/support/tickets/'
      path: '/support/tickets'
      fullPath: '/support/tickets/'
      preLoaderRoute: typeof AuthenticatedSupportTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/tickets/$id': {
      id: '/_authenticated/support/tickets/$id'
      path: '/support/tickets/$id'
      fullPath: '/support/tickets/$id'
      preLoaderRoute: typeof AuthenticatedSupportTicketsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBugsRoute: typeof AuthenticatedBugsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedCrmClientsRoute: typeof AuthenticatedCrmClientsRoute
  AuthenticatedCrmCompaniesRoute: typeof AuthenticatedCrmCompaniesRoute
  AuthenticatedCrmContactsRoute: typeof AuthenticatedCrmContactsRoute
  AuthenticatedCrmContractsRoute: typeof AuthenticatedCrmContractsRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmMeetingsRoute: typeof AuthenticatedCrmMeetingsRoute
  AuthenticatedCrmQuotationsRoute: typeof AuthenticatedCrmQuotationsRoute
  AuthenticatedFinanceExpensesRoute: typeof AuthenticatedFinanceExpensesRoute
  AuthenticatedFinanceInvoicesRoute: typeof AuthenticatedFinanceInvoicesRoute
  AuthenticatedFinancePaymentsRoute: typeof AuthenticatedFinancePaymentsRoute
  AuthenticatedFinanceRevenueRoute: typeof AuthenticatedFinanceRevenueRoute
  AuthenticatedHostingAccountsRoute: typeof AuthenticatedHostingAccountsRoute
  AuthenticatedHostingDomainsRoute: typeof AuthenticatedHostingDomainsRoute
  AuthenticatedHostingServersRoute: typeof AuthenticatedHostingServersRoute
  AuthenticatedHostingSslRoute: typeof AuthenticatedHostingSslRoute
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrDepartmentsRoute: typeof AuthenticatedHrDepartmentsRoute
  AuthenticatedHrEmployeesRoute: typeof AuthenticatedHrEmployeesRoute
  AuthenticatedHrLeavesRoute: typeof AuthenticatedHrLeavesRoute
  AuthenticatedHrPayrollRoute: typeof AuthenticatedHrPayrollRoute
  AuthenticatedMarketingAccountsRoute: typeof AuthenticatedMarketingAccountsRoute
  AuthenticatedMarketingActivityRoute: typeof AuthenticatedMarketingActivityRoute
  AuthenticatedMarketingCampaignsRoute: typeof AuthenticatedMarketingCampaignsRoute
  AuthenticatedMarketingContentRoute: typeof AuthenticatedMarketingContentRoute
  AuthenticatedMarketingDashboardRoute: typeof AuthenticatedMarketingDashboardRoute
  AuthenticatedMarketingLandingRoute: typeof AuthenticatedMarketingLandingRoute
  AuthenticatedMarketingPipelineRoute: typeof AuthenticatedMarketingPipelineRoute
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
  AuthenticatedSupportAgentsRoute: typeof AuthenticatedSupportAgentsRoute
  AuthenticatedSupportAutomationRoute: typeof AuthenticatedSupportAutomationRoute
  AuthenticatedSupportCannedResponsesRoute: typeof AuthenticatedSupportCannedResponsesRoute
  AuthenticatedSupportChatHistoryRoute: typeof AuthenticatedSupportChatHistoryRoute
  AuthenticatedSupportDashboardRoute: typeof AuthenticatedSupportDashboardRoute
  AuthenticatedSupportDepartmentsRoute: typeof AuthenticatedSupportDepartmentsRoute
  AuthenticatedSupportInboxRoute: typeof AuthenticatedSupportInboxRoute
  AuthenticatedSupportKnowledgeBaseRoute: typeof AuthenticatedSupportKnowledgeBaseRoute
  AuthenticatedSupportQueueRoute: typeof AuthenticatedSupportQueueRoute
  AuthenticatedSupportReportsRoute: typeof AuthenticatedSupportReportsRoute
  AuthenticatedSupportSlaRoute: typeof AuthenticatedSupportSlaRoute
  AuthenticatedSupportWidgetRoute: typeof AuthenticatedSupportWidgetRoute
  AuthenticatedMarketingIndexRoute: typeof AuthenticatedMarketingIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedSupportIndexRoute: typeof AuthenticatedSupportIndexRoute
  AuthenticatedSupportTicketsIdRoute: typeof AuthenticatedSupportTicketsIdRoute
  AuthenticatedSupportTicketsIndexRoute: typeof AuthenticatedSupportTicketsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBugsRoute: AuthenticatedBugsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedCrmClientsRoute: AuthenticatedCrmClientsRoute,
  AuthenticatedCrmCompaniesRoute: AuthenticatedCrmCompaniesRoute,
  AuthenticatedCrmContactsRoute: AuthenticatedCrmContactsRoute,
  AuthenticatedCrmContractsRoute: AuthenticatedCrmContractsRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmMeetingsRoute: AuthenticatedCrmMeetingsRoute,
  AuthenticatedCrmQuotationsRoute: AuthenticatedCrmQuotationsRoute,
  AuthenticatedFinanceExpensesRoute: AuthenticatedFinanceExpensesRoute,
  AuthenticatedFinanceInvoicesRoute: AuthenticatedFinanceInvoicesRoute,
  AuthenticatedFinancePaymentsRoute: AuthenticatedFinancePaymentsRoute,
  AuthenticatedFinanceRevenueRoute: AuthenticatedFinanceRevenueRoute,
  AuthenticatedHostingAccountsRoute: AuthenticatedHostingAccountsRoute,
  AuthenticatedHostingDomainsRoute: AuthenticatedHostingDomainsRoute,
  AuthenticatedHostingServersRoute: AuthenticatedHostingServersRoute,
  AuthenticatedHostingSslRoute: AuthenticatedHostingSslRoute,
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrDepartmentsRoute: AuthenticatedHrDepartmentsRoute,
  AuthenticatedHrEmployeesRoute: AuthenticatedHrEmployeesRoute,
  AuthenticatedHrLeavesRoute: AuthenticatedHrLeavesRoute,
  AuthenticatedHrPayrollRoute: AuthenticatedHrPayrollRoute,
  AuthenticatedMarketingAccountsRoute: AuthenticatedMarketingAccountsRoute,
  AuthenticatedMarketingActivityRoute: AuthenticatedMarketingActivityRoute,
  AuthenticatedMarketingCampaignsRoute: AuthenticatedMarketingCampaignsRoute,
  AuthenticatedMarketingContentRoute: AuthenticatedMarketingContentRoute,
  AuthenticatedMarketingDashboardRoute: AuthenticatedMarketingDashboardRoute,
  AuthenticatedMarketingLandingRoute: AuthenticatedMarketingLandingRoute,
  AuthenticatedMarketingPipelineRoute: AuthenticatedMarketingPipelineRoute,
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
  AuthenticatedSupportAgentsRoute: AuthenticatedSupportAgentsRoute,
  AuthenticatedSupportAutomationRoute: AuthenticatedSupportAutomationRoute,
  AuthenticatedSupportCannedResponsesRoute:
    AuthenticatedSupportCannedResponsesRoute,
  AuthenticatedSupportChatHistoryRoute: AuthenticatedSupportChatHistoryRoute,
  AuthenticatedSupportDashboardRoute: AuthenticatedSupportDashboardRoute,
  AuthenticatedSupportDepartmentsRoute: AuthenticatedSupportDepartmentsRoute,
  AuthenticatedSupportInboxRoute: AuthenticatedSupportInboxRoute,
  AuthenticatedSupportKnowledgeBaseRoute:
    AuthenticatedSupportKnowledgeBaseRoute,
  AuthenticatedSupportQueueRoute: AuthenticatedSupportQueueRoute,
  AuthenticatedSupportReportsRoute: AuthenticatedSupportReportsRoute,
  AuthenticatedSupportSlaRoute: AuthenticatedSupportSlaRoute,
  AuthenticatedSupportWidgetRoute: AuthenticatedSupportWidgetRoute,
  AuthenticatedMarketingIndexRoute: AuthenticatedMarketingIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedSupportIndexRoute: AuthenticatedSupportIndexRoute,
  AuthenticatedSupportTicketsIdRoute: AuthenticatedSupportTicketsIdRoute,
  AuthenticatedSupportTicketsIndexRoute: AuthenticatedSupportTicketsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAiSolutionsRoute: typeof PublicAiSolutionsRoute
  PublicClientsRoute: typeof PublicClientsRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicDomainsRoute: typeof PublicDomainsRoute
  PublicDownloadsRoute: typeof PublicDownloadsRoute
  PublicEventsRoute: typeof PublicEventsRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicHostingRoute: typeof PublicHostingRoute
  PublicIndustriesRoute: typeof PublicIndustriesRoute
  PublicMaintenanceRoute: typeof PublicMaintenanceRoute
  PublicPartnersRoute: typeof PublicPartnersRoute
  PublicPressRoute: typeof PublicPressRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResourcesRoute: typeof PublicResourcesRoute
  PublicStatusRoute: typeof PublicStatusRoute
  PublicSupportRoute: typeof PublicSupportRoute
  PublicTeamRoute: typeof PublicTeamRoute
  PublicTechnologiesRoute: typeof PublicTechnologiesRoute
  PublicTestimonialsRoute: typeof PublicTestimonialsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicCareersSlugRoute: typeof PublicCareersSlugRoute
  PublicCaseStudiesSlugRoute: typeof PublicCaseStudiesSlugRoute
  PublicDocsSlugRoute: typeof PublicDocsSlugRoute
  PublicLegalDocRoute: typeof PublicLegalDocRoute
  PublicPortfolioSlugRoute: typeof PublicPortfolioSlugRoute
  PublicProductsSlugRoute: typeof PublicProductsSlugRoute
  PublicServicesSlugRoute: typeof PublicServicesSlugRoute
  PublicSolutionsIndustryRoute: typeof PublicSolutionsIndustryRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicCareersIndexRoute: typeof PublicCareersIndexRoute
  PublicCaseStudiesIndexRoute: typeof PublicCaseStudiesIndexRoute
  PublicDocsIndexRoute: typeof PublicDocsIndexRoute
  PublicPortfolioIndexRoute: typeof PublicPortfolioIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
  PublicSolutionsIndexRoute: typeof PublicSolutionsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicAiSolutionsRoute: PublicAiSolutionsRoute,
  PublicClientsRoute: PublicClientsRoute,
  PublicContactRoute: PublicContactRoute,
  PublicDomainsRoute: PublicDomainsRoute,
  PublicDownloadsRoute: PublicDownloadsRoute,
  PublicEventsRoute: PublicEventsRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicHostingRoute: PublicHostingRoute,
  PublicIndustriesRoute: PublicIndustriesRoute,
  PublicMaintenanceRoute: PublicMaintenanceRoute,
  PublicPartnersRoute: PublicPartnersRoute,
  PublicPressRoute: PublicPressRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResourcesRoute: PublicResourcesRoute,
  PublicStatusRoute: PublicStatusRoute,
  PublicSupportRoute: PublicSupportRoute,
  PublicTeamRoute: PublicTeamRoute,
  PublicTechnologiesRoute: PublicTechnologiesRoute,
  PublicTestimonialsRoute: PublicTestimonialsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicCareersSlugRoute: PublicCareersSlugRoute,
  PublicCaseStudiesSlugRoute: PublicCaseStudiesSlugRoute,
  PublicDocsSlugRoute: PublicDocsSlugRoute,
  PublicLegalDocRoute: PublicLegalDocRoute,
  PublicPortfolioSlugRoute: PublicPortfolioSlugRoute,
  PublicProductsSlugRoute: PublicProductsSlugRoute,
  PublicServicesSlugRoute: PublicServicesSlugRoute,
  PublicSolutionsIndustryRoute: PublicSolutionsIndustryRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicCareersIndexRoute: PublicCareersIndexRoute,
  PublicCaseStudiesIndexRoute: PublicCaseStudiesIndexRoute,
  PublicDocsIndexRoute: PublicDocsIndexRoute,
  PublicPortfolioIndexRoute: PublicPortfolioIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
  PublicSolutionsIndexRoute: PublicSolutionsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
